import { PaymentItem } from '../classes/paymentItem';

export const PAYMENTITEMS: PaymentItem[] = [
    { id: 1, categoryID: 1, description: "Emergency", amount: 200, dueDay: [1,15] },
    { id: 2, categoryID: 1, description: "Christmas", amount: 50, dueDay: [15] },
    { id: 3, categoryID: 1, description: "Birthday", amount: 30, dueDay: [15] },
    { id: 4, categoryID: 1, description: "Clothing", amount: 100, dueDay: [1] },
    { id: 5, categoryID: 1, description: "Home Maintenance", amount: 200, dueDay: [15] },
    { id: 6, categoryID: 1, description: "Vehicle Maintenance", amount: 130, dueDay: [15] },
    { id: 7, categoryID: 1, description: "ATV", amount: 80, dueDay: [31] },
    { id: 8, categoryID: 2, description: "Car Insurance", amount: 255, dueDay: [8] },
    { id: 9, categoryID: 2, description: "Electric", amount: 223, dueDay: [22] },
    { id: 10, categoryID: 2, description: "Phone", amount: 185, dueDay: [1] },
    { id: 11, categoryID: 2, description: "Trash", amount: 30, dueDay: [22] },
    { id: 13, categoryID: 3, description: "Gas", amount: 300, dueDay: [1,15] },
    { id: 14, categoryID: 3, description: "Groceries", amount: 1200, dueDay: [1,8,15,22,29] },
    { id: 15, categoryID: 3, description: "Necessities", amount: 300, dueDay: [1,8,15,22,29] },
    { id: 16, categoryID: 3, description: "Netflix", amount: 11, dueDay: [17] },
    { id: 17, categoryID: 3, description: "Entertainment", amount: 800, dueDay: [1,15] },
    { id: 18, categoryID: 4, description: "Rent", amount: 400, dueDay: [1] },
    { id: 19, categoryID: 4, description: "Insurance", amount: 60, dueDay: [3] },
    { id: 20, categoryID: 4, description: "Repair", amount: 400, dueDay: [18] },
    { id: 21, categoryID: 5, description: "Electric", amount: 120, dueDay: [31] },
    { id: 22, categoryID: 5, description: "Water", amount: 30, dueDay: [12] },
    { id: 23, categoryID: 5, description: "Propane", amount: 112, dueDay: [16] },
    { id: 24, categoryID: 5, description: "Trash", amount: 20, dueDay: [12] },
    { id: 25, categoryID: 5, description: "Cable", amount: 70, dueDay: [31] },
    { id: 26, categoryID: 5, description: "Phone", amount: 65, dueDay: [24] },
    { id: 27, categoryID: 6, description: "Groceries", amount: 700, dueDay: [1, 15] },
    { id: 28, categoryID: 6, description: "Toiletries", amount: 200, dueDay: [1, 15] },
    { id: 29, categoryID: 6, description: "Gas", amount: 180, dueDay: [1,8,15,22,29] },    
];